[package]
name = "rust-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eks-blueprints-rust-sdk = "0.1.1"
tokio = "1.29.1"
tonic = "0.9.2"
